=== ks4049/XML-Recipe-Project/validate_recipe.dtd
<!ELEMENT Recipe (recipe_name,recipe_image,recipe_by,serves,ingredients,procedure,hints?)>
<!ELEMENT recipe_name (#PCDATA)>
<!ELEMENT recipe_image (#PCDATA)>
<!ELEMENT recipe_by (#PCDATA)>
<!ELEMENT serves (#PCDATA)>
<!ELEMENT ingredients (ingredient+)>
<!ELEMENT ingredient (#PCDATA)>
<!ELEMENT procedure (step+)>
<!ELEMENT step (#PCDATA)>
<!ELEMENT hints (#PCDATA)>

=== ks4049/XML-Recipe-Project/Recipe2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Recipe_Style.xslt"?>
<!DOCTYPE Recipe SYSTEM "validate_recipe.dtd">
<Recipe>
	<recipe_name>Chicken Saltimbocca</recipe_name>
	<recipe_image>Chicken.jpg</recipe_image>
	<recipe_by> Dan Eaton </recipe_by>
	<serves>2-4 </serves>
	<ingredients>
		<ingredient>4 chicken cutlets</ingredient>
		<ingredient>4 whole fresh sage leaves (plus 2-3 tsp chopped sage)</ingredient>
		<ingredient>4 thin slices prosciutto (or more or less as needed)</ingredient>
		<ingredient>Olive oil for sautéing chicken</ingredient>
		<ingredient>1 Tbs butter</ingredient>
		<ingredient>6-8 ounces sliced mushrooms</ingredient>
		<ingredient>1/4 cup finely diced onion</ingredient>
		<ingredient>1/2 cup Marsala wine</ingredient>
		<ingredient>1/2 cup chicken stock</ingredient>
		<ingredient>Salt and pepper to taste</ingredient>
		<ingredient>More butter as needed to help thicken final sauce (optional)</ingredient>
	</ingredients>
	<procedure>
		<step>Place the chicken cutlets on top of a sheet of plastic wrap and place one fresh sage leaf of top of each one, top each one with a thin layer of prosciutto, place another sheet of plastic wrap on top and use a meat hammer or rolling pin to pound the chicken so that the prosciutto adheres. </step>

		<step> Add a good splash of olive oil to a large heavy bottomed pan on medium high heat and, when the oil is hot; carefully add the chicken...prosciutto side down. </step>

		<step> Once the prosciutto has crisped up nicely, flip the chicken and keep cooking it on the second side. </step>

		<step> Take the chicken out of the pan and let it rest on a clean plate, it doesn't need to be cooked all the way through at this point because you will finish cooking it in the sauce later on. </step>

		<step> Add a dollop of butter to the pan and then add 6-8 ounces of sliced mushrooms and about 1/4 cup finely diced onion and 2-3 tsp fresh chopped sage and get those going. </step>

		<step> Once the mushrooms have cooked down a bit, add 1/2 cup Marsala wine and 1/2 cup chicken stock turn the heat to high and let it cook down to a sauce consistency. </step>

		<step> When the sauce is just about there, add the chicken back to the pan to finish cooking through and it's time to eat. </step>
	</procedure>
	<hints>
		Serve with rice or simple olive oil dress pasta. Depending on how hungry you are….you may want more than one cutlet per serving.
	</hints>
</Recipe>

=== ks4049/XML-Recipe-Project/Recipe1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Recipe_Style.xslt"?>
<!DOCTYPE Recipe SYSTEM "validate_recipe.dtd">
<Recipe>
	<recipe_name>Buttermilk Fried Sweet Onion Rings</recipe_name>
	<recipe_image>Fried-Onion-Ring.jpg</recipe_image>
	<recipe_by> Dan Eaton </recipe_by>
	<serves>4-6 as a side</serves>
	<ingredients>
		<ingredient>2 large sweet onions (Vidalia, Texas or Mayan Sweet)</ingredient>
		<ingredient>Approx. 1 quart buttermilk</ingredient>
		<ingredient>4 cups vegetable oil for deep frying</ingredient>
		<ingredient>1 1/2 cups all-purpose flour</ingredient>
		<ingredient>1/4 cup cornmeal</ingredient>
		<ingredient>1 Tbs finely minced fresh rosemary (optional but good)</ingredient>
		<ingredient>Pinch salt</ingredient>
		<ingredient>1/2 tsp ground cayenne</ingredient>
		<ingredient>Salt to taste after frying</ingredient>
	</ingredients>
	<procedure>
		<step>	Get started by cutting the tops and bottoms off of the onions, then peeling them and cutting them crosswise into rings about 1/2-inch thick. </step>

		<step> Separate the slices onions into individual rings and place those into a large baking dish and add enough buttermilk to just about cover. </step>

		<step> Let the onions soak in the buttermilk for at least 15 minutes and, while that's happening, add 4 cups of vegetable oil to a deep stainless steel pot on the stovetop and slowly bring that up to 360 degrees. </step>

		<step> Use a bowl to combine 1 1/2 cups all-purpose flour with 1/4 cup cornmeal and 1 optional Tbs finely chopped fresh rosemary and a pinch of cayenne pepper and a pinch of salt and mix it up. </step>

		<step> Use a deep fry thermometer to keep an eye on the temperature of the oil and also preheat the oven to 200 degrees and line a baking tray with paper towels, with a cooling rack on top, so you can keep the onion rings warm in the oven as you go. </step>

		<step> When the oil is hot enough, dredge 5-6 onion rings at a time in the flour mixture and, once the oil does hit 360 degrees, very carefully add 1 onion ring at a time and let those fry along until they turn a nice golden brown. </step>

		<step> You may have to adjust the heat a little bit as you're adding the onion rings so the oil stays at 360 degrees and once they're a nice golden brown, take them out of the oil and place them on the cooling rack, season with salt to taste and place the tray into the oven to keep warm as you're doing the other onion rings. </step>
	</procedure>
	<hints>
		Use the leftover buttermilk for something like cornbread or biscuits instead of tossing it out.
		You may need to sift the dredging flour at some point during the process or add more flour as needed.
	</hints>
</Recipe>

=== ks4049/XML-Recipe-Project/Recipe3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Recipe_Style.xslt"?>
<!DOCTYPE Recipe SYSTEM "validate_recipe.dtd">
<Recipe>
	<recipe_name>Moist Banana Bread </recipe_name>
	<recipe_image>Banana-Bread.jpg</recipe_image>
	<recipe_by> Natasha </recipe_by>	
	<serves>10</serves>
	<ingredients>
		<ingredient>3 (medium/large) ripe bananas mashed with a fork</ingredient>
		<ingredient>1/2 cup unsalted butter (8 Tbsp) at room temperature</ingredient>
		<ingredient>3/4 cup white sugar</ingredient>
		<ingredient>2 eggs lightly beaten</ingredient>
		<ingredient>1 ½ cups all-purpose flour</ingredient>
		<ingredient>1 tsp baking soda</ingredient>
		<ingredient>1/2 tsp salt</ingredient>
		<ingredient>1/2 tsp vanilla</ingredient>
		<ingredient>1 cup walnuts</ingredient>
		<ingredient>1/2 cup raisins</ingredient>
	</ingredients>
	<procedure>
		<step>Preheat the oven to 350°F.  </step>
		<step> Grease and flour a bread loaf pan (9.25 long x 5.25 wide x 2.75 deep). </step>
		<step> Lightly roast walnuts on a skillet, continuously stirring so they won’t burn. </step>
		<step> Coarsely chop and cool to room temperature.  </step>

		<step> In a mixing bowl, cream together 8 Tbsp softened butter and 3/4 cup sugar (or honey if using honey). </step>

		<step> Mash bananas with a fork until the consistency of chunky applesauce and add them to the batter along with 2 eggs, mixing until blended. </step>

		<step> In a separate bowl, whisk together: 1 1/2 cups of flour, 1 tsp of baking soda and 1/2 tsp of salt then add to batter. </step>
		<step> Add 1/2 tsp of vanilla extract and mix in chopped walnuts and raisins. </step>

		<step> Pour into prepared loaf pan. </step>

		<step> Bake at 350˚F for 55-60 min or until a toothpick inserted into the center comes out clean. </step>
		
		<step> Let banana bread rest for 10 min before transferring to wire rack to cool. </step>
	</procedure>
	<hints>
		To ripen bananas quickly, put them into a paper bag and fold down the top. The bananas should ripen in 2 days.
	</hints>
</Recipe>
